events {
    worker_connections  4096;
}
http{
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server {
        listen 80;
        root /usr/share/nginx/html;

        location /reserve/assets/ {
            alias /usr/share/nginx/html/assets/;
            access_log off;
            add_header Cache-Control "public, max-age=31536000, immutable";
            try_files $uri =404;
        }

        location /reserve/ {
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}